# Site settings
title: home
header-img: img/home-bg.jpg
email:
copyright_name: Vin/cheerUp!
description: "加油"
baseurl: ""
url: ""
twitter_username: SBootstrap
github_username:
facebook_username:
email_username:

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
